version: '3.4'

networks:
  democrudapp:
services:
  crude:
    container_name: crude
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment: 
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password@1234"
      UserID: "sa"
      
    networks:
      - democrudapp


  crudeapp:
    image: ${DOCKER_REGISTRY-}crudeapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    depends_on: 
      - crude

    networks:
      - democrudapp