version: '3.4'

services:
  crude:
    container_name: crude
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password@1234"
      MSSQL_PID: Express


  crudeapp:
    image: ${DOCKER_REGISTRY-}crudeapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    depends_on: 
      - crude
    environment: 
      DB_HOST: "crude"
      DB_NAME: "CrudeApp"
      DB_PORT: "1433"
      DB_SA_PASSWORD: "Password@1234"
      DB_USER: "SA"
